import { describe, expect, it, vi } from "vitest";
import {
  shouldDescribePr,
  renderDescriptionBlock,
  embedPrDescription,
  buildDescriptionSystem,
  buildDescriptionPrompt,
  generatePrDescription,
  PR_SUMMARY_START,
  PR_SUMMARY_END
} from "../src/review/pr-description.js";
import type { ProviderConfig } from "../src/providers/types.js";

const config: ProviderConfig = { provider: "anthropic", model: "m", apiKey: "k" };

describe("shouldDescribePr", () => {
  it("is true for an empty/whitespace body", () => {
    expect(shouldDescribePr(null)).toBe(true);
    expect(shouldDescribePr("")).toBe(true);
    expect(shouldDescribePr("   \n  ")).toBe(true);
  });

  it("is true when the body already holds our generated block (refresh)", () => {
    expect(shouldDescribePr(`intro\n${PR_SUMMARY_START}\nold\n${PR_SUMMARY_END}`)).toBe(true);
  });

  it("is false for a human-authored body (never overwrite)", () => {
    expect(shouldDescribePr("This PR fixes the login bug.")).toBe(false);
  });
});

describe("renderDescriptionBlock / embedPrDescription", () => {
  it("wraps the description in attributed start/end markers", () => {
    const block = renderDescriptionBlock("- did a thing");
    expect(block.startsWith(PR_SUMMARY_START)).toBe(true);
    expect(block.trimEnd().endsWith(PR_SUMMARY_END)).toBe(true);
    expect(block).toContain("## Summary");
    expect(block).toContain("- did a thing");
    expect(block).toContain("Generated by prowl-review");
  });

  it("sets the whole body when it was empty", () => {
    const body = embedPrDescription("", "overview");
    expect(body).toBe(renderDescriptionBlock("overview"));
  });

  it("replaces an existing block in place, preserving text around it", () => {
    const existing = `Author intro.\n\n${PR_SUMMARY_START}\n## Summary\n\nold\n${PR_SUMMARY_END}\n\nAuthor footer.`;
    const body = embedPrDescription(existing, "fresh summary");
    expect(body).toContain("Author intro.");
    expect(body).toContain("Author footer.");
    expect(body).toContain("fresh summary");
    expect(body).not.toContain("old");
    // Exactly one block remains.
    expect(body.match(new RegExp(PR_SUMMARY_START, "g"))).toHaveLength(1);
  });
});

describe("buildDescriptionPrompt / system", () => {
  it("frames the title + diff as untrusted data", () => {
    const prompt = buildDescriptionPrompt({ title: "Add cache", diff: "diff --git a b" });
    expect(prompt).toContain("untrusted data");
    expect(prompt).toContain("Add cache");
    expect(prompt).toContain("diff --git a b");
  });

  it("system prompt carries the injection guard + optional guidelines", () => {
    expect(buildDescriptionSystem()).toContain("untrusted DATA");
    expect(buildDescriptionSystem("Use conventional commits")).toContain("Use conventional commits");
  });

  it("redacts secrets from the title and diff before prompting", () => {
    const secret = ["AKIA", "1234567890ABCD99"].join("");
    const prompt = buildDescriptionPrompt({ title: `key ${secret}`, diff: `+const k = "${secret}"` });
    expect(prompt).not.toContain(secret);
  });
});

describe("generatePrDescription", () => {
  it("calls the provider and returns sanitized markdown + usage", async () => {
    const complete = vi.fn().mockResolvedValue({
      text: "## overview\n- changed @everyone <script>",
      usage: { inputTokens: 10, outputTokens: 5, cachedInputTokens: 0 }
    });
    const { description, usage } = await generatePrDescription(
      { title: "t", diff: "d" },
      { config, deps: { complete } }
    );
    expect(complete).toHaveBeenCalledTimes(1);
    expect(usage.inputTokens).toBe(10);
    // Mentions neutralized, raw HTML escaped by the shared sanitizer.
    expect(description).not.toContain("@everyone");
    expect(description).toContain("&#64;everyone");
    expect(description).not.toContain("<script>");
  });
});
