import { describe, expect, it, vi } from "vitest";
import {
  shouldDescribePr,
  renderDescriptionBlock,
  embedPrDescription,
  buildDescriptionSystem,
  buildDescriptionPrompt,
  generatePrDescription,
  PR_SUMMARY_START,
  PR_SUMMARY_END
} from "../src/review/pr-description.js";
import type { ProviderConfig } from "../src/providers/index.js";

const config: ProviderConfig = { provider: "anthropic", model: "m", apiKey: "k" };

describe("shouldDescribePr", () => {
  it("is true for an empty/whitespace body", () => {
    expect(shouldDescribePr(null)).toBe(true);
    expect(shouldDescribePr("")).toBe(true);
    expect(shouldDescribePr("   \n  ")).toBe(true);
  });

  it("is true when the body already holds our generated block (refresh)", () => {
    expect(shouldDescribePr(`intro\n${PR_SUMMARY_START}\nold\n${PR_SUMMARY_END}`)).toBe(true);
  });

  it("is false for a human-authored body (never overwrite)", () => {
    expect(shouldDescribePr("This PR fixes the login bug.")).toBe(false);
  });

  it("is false when only one marker is present", () => {
    expect(shouldDescribePr(`intro\n${PR_SUMMARY_START}\nmanual text`)).toBe(false);
    expect(shouldDescribePr(`intro\n${PR_SUMMARY_END}\nmanual text`)).toBe(false);
  });
});

describe("renderDescriptionBlock / embedPrDescription", () => {
  it("wraps the description in attributed start/end markers", () => {
    const block = renderDescriptionBlock("- did a thing");
    expect(block.startsWith(PR_SUMMARY_START)).toBe(true);
    expect(block.trimEnd().endsWith(PR_SUMMARY_END)).toBe(true);
    expect(block).toContain("## Summary");
    expect(block).toContain("- did a thing");
    expect(block).toContain("Generated by prowl-review");
  });

  it("sets the whole body when it was empty", () => {
    const body = embedPrDescription("", "overview");
    expect(body).toBe(renderDescriptionBlock("overview"));
  });

  it("replaces an existing block in place, preserving text around it", () => {
    const existing = `Author intro.\n\n${PR_SUMMARY_START}\n## Summary\n\nold\n${PR_SUMMARY_END}\n\nAuthor footer.`;
    const body = embedPrDescription(existing, "fresh summary");
    expect(body).toContain("Author intro.");
    expect(body).toContain("Author footer.");
    expect(body).toContain("fresh summary");
    expect(body).not.toContain("old");
    // Exactly one block remains.
    expect(body.match(new RegExp(PR_SUMMARY_START, "g"))).toHaveLength(1);
  });

  it("leaves malformed marker-like bodies unchanged", () => {
    const startOnly = `Author intro.\n\n${PR_SUMMARY_START}\nmanual text`;
    const endOnly = `Author intro.\n\n${PR_SUMMARY_END}\nmanual text`;
    const reversed = `Author intro.\n\n${PR_SUMMARY_END}\nmanual text\n${PR_SUMMARY_START}`;

    expect(embedPrDescription(startOnly, "fresh summary")).toBe(startOnly);
    expect(embedPrDescription(endOnly, "fresh summary")).toBe(endOnly);
    expect(embedPrDescription(reversed, "fresh summary")).toBe(reversed);
  });

  it("is idempotent when called repeatedly on a generated block", () => {
    const once = embedPrDescription("", "fresh summary");
    const twice = embedPrDescription(once, "fresh summary");

    expect(twice).toBe(once);
    expect(twice.match(new RegExp(PR_SUMMARY_START, "g"))).toHaveLength(1);
    expect(twice.match(new RegExp(PR_SUMMARY_END, "g"))).toHaveLength(1);
  });

  it("never leaves a partial generated block after truncation", () => {
    const nearLimitBody = "x".repeat(65_520);
    const body = embedPrDescription(nearLimitBody, "fresh summary");

    expect(body.length).toBeLessThanOrEqual(65_536);
    expect(body.includes(PR_SUMMARY_START)).toBe(body.includes(PR_SUMMARY_END));
  });

  it("preserves author text around the generated block near the body limit", () => {
    const intro = "a".repeat(32_600);
    const footer = "b".repeat(32_600);
    const existing = `${intro}\n\n${renderDescriptionBlock("old summary")}\n\n${footer}`;
    const body = embedPrDescription(existing, "fresh summary ".repeat(1_000));

    expect(body.length).toBeLessThanOrEqual(65_536);
    expect(body).toContain(intro);
    expect(body).toContain(PR_SUMMARY_START);
    expect(body).toContain("fresh summary");
    expect(body).toContain(footer);
    expect(body.includes(PR_SUMMARY_START)).toBe(body.includes(PR_SUMMARY_END));
  });

  it("does not split UTF-16 surrogate pairs when shrinking generated text", () => {
    const emptyBlockLength = renderDescriptionBlock("").length;
    const descriptionBudget = 2;
    const authorText = "a".repeat(65_536 - "\n\n".length - emptyBlockLength - descriptionBudget);
    const body = embedPrDescription(authorText, "x😀tail");

    expect(body.length).toBeLessThanOrEqual(65_536);
    expect(body).toContain("## Summary\n\nx\n\n");
    expect(body).not.toContain("😀");
    expect(body).not.toContain("\uD83D");
  });

  it("replaces only the first complete generated block when multiple blocks are present", () => {
    const secondBlock = renderDescriptionBlock("second generated block");
    const existing = `Author intro.\n\n${renderDescriptionBlock("first generated block")}\n\nSecond block:\n${secondBlock}`;
    const body = embedPrDescription(existing, "fresh summary");

    expect(body).toContain("Author intro.");
    expect(body).toContain("fresh summary");
    expect(body).not.toContain("first generated block");
    expect(body).toContain("Second block:");
    expect(body).toContain("second generated block");
    expect(body.match(new RegExp(PR_SUMMARY_START, "g"))).toHaveLength(2);
    expect(body.match(new RegExp(PR_SUMMARY_END, "g"))).toHaveLength(2);
  });
});

describe("buildDescriptionPrompt / system", () => {
  it("frames the title + diff as untrusted data", () => {
    const prompt = buildDescriptionPrompt({ title: "Add cache", diff: "diff --git a b" });
    expect(prompt).toContain("untrusted data");
    expect(prompt).toContain("Add cache");
    expect(prompt).toContain("diff --git a b");
  });

  it("system prompt carries the injection guard + optional guidelines", () => {
    expect(buildDescriptionSystem()).toContain("untrusted DATA");
    expect(buildDescriptionSystem("Use conventional commits")).toContain("Use conventional commits");
  });

  it("redacts secrets from the title and diff before prompting", () => {
    const secret = ["AKIA", "1234567890ABCD99"].join("");
    const prompt = buildDescriptionPrompt({ title: `key ${secret}`, diff: `+const k = "${secret}"` });
    expect(prompt).not.toContain(secret);
  });

  it("uses already-redacted prompt input as-is", () => {
    const prompt = buildDescriptionPrompt({
      title: "key [REDACTED:aws-access-key]",
      diff: '+const k = "[REDACTED:aws-access-key]"',
      alreadyRedacted: true
    });
    expect(prompt).toContain("[REDACTED:aws-access-key]");
  });
});

describe("generatePrDescription", () => {
  it("calls the provider and returns sanitized markdown + usage", async () => {
    const complete = vi.fn().mockResolvedValue({
      text: "## overview\n- changed @everyone <script>",
      usage: { inputTokens: 10, outputTokens: 5, cachedInputTokens: 0 }
    });
    const { description, usage } = await generatePrDescription(
      { title: "t", diff: "d" },
      { config, deps: { complete } }
    );
    expect(complete).toHaveBeenCalledTimes(1);
    expect(usage.inputTokens).toBe(10);
    // Mentions neutralized, raw HTML escaped by the shared sanitizer.
    expect(description).not.toContain("@everyone");
    expect(description).toContain("&#64;everyone");
    expect(description).not.toContain("<script>");
  });

  it("keeps the default description cap for non-Gemini providers", async () => {
    const complete = vi.fn().mockResolvedValue({
      text: "summary",
      usage: { inputTokens: 1, outputTokens: 1, cachedInputTokens: 0 }
    });

    await generatePrDescription({ title: "t", diff: "d" }, { config, deps: { complete } });

    expect(complete.mock.calls[0][0]).toEqual(expect.objectContaining({ maxTokens: 1024 }));
  });

  it("lets Gemini use the provider output-token default unless explicitly capped", async () => {
    const geminiConfig: ProviderConfig = { provider: "gemini", model: "gemini-2.5-pro", apiKey: "k" };
    const complete = vi.fn().mockResolvedValue({
      text: "summary",
      usage: { inputTokens: 1, outputTokens: 1, cachedInputTokens: 0 }
    });

    await generatePrDescription({ title: "t", diff: "d" }, { config: geminiConfig, deps: { complete } });
    expect(complete.mock.calls[0][0]).not.toHaveProperty("maxTokens");

    await generatePrDescription(
      { title: "t", diff: "d" },
      { config: geminiConfig, maxTokens: 4096, deps: { complete } }
    );
    expect(complete.mock.calls[1][0]).toEqual(expect.objectContaining({ maxTokens: 4096 }));
  });
});
